env:
  global:
    - CC_TEST_REPORTER_ID=ca13c8a4bf4c4707d4403cdc2110998a510eedca0919e926e7bce6daafd59544

language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2

sudo: false

addons:
  code_climate:
    repo_token: ca13c8a4bf4c4707d4403cdc2110998a510eedca0919e926e7bce6daafd59544

install:
    - pecl install mongodb
    - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
